language: php
php:
  - 5.6
  - 7.0
  - 7.1
install:
  - pecl install yaf
  - echo "extension=yaf.so" >> ~/.phpenv/versions/$(phpenv version-name)/etc/php.ini
  - composer update
script:
  - vendor/bin/phpunit